### PR TITLE
Re-Updated the code

### PR DESCRIPTION
**Pull request by Soyvor**
Updates 

mainactivity.java
resultdialog.java

tried to remove all the errors , check again

### CODE REVIEW

**Comment by Soyvor** [comment]
please label me on hacktober fest i closed the last one by mistake sorry

**Comment by lovishprabhakar** [comment]
Good work, @Soyvor. But two errors are still there. I'm attaching the screenshots, fix them and then your PR will be merged.

1. Need to add the reset button in the layout file.
image

2. There is no function called restartMatch in MainActivity. You are probably referring to restartGame function.
 
image

**Comment by Soyvor** [comment]
okay

**Comment by lovishprabhakar** [comment]
@Soyvor status update?

**Comment by lovishprabhakar** [comment]
@Soyvor last call, are you working on this or shall I close this issue and PR?

**Pull request closed without merging**
